### ISSUE TITLE
Git indicators mess up fuzzy finder

### ISSUE THREAD

**Issue by despairblue** [ignism/graphite-ui#1]
The git indicators indicating whether a file is new or changed etc is shown avove the files in the fuzzy finder instead of next to them.
![screenshot from 2014-12-23 22 34 21](https://cloud.githubusercontent.com/assets/927609/5543388/d485a5c8-8af3-11e4-8d1e-bd9735e65d8e.png)

Besides that, this is one of the best themes I've ever seen. Great work!

**Comment by despairblue** [comment]
Adding

``` less
.status.icon {
  float: right;
}
```

somewhere fixes this.

**Comment by ignism** [comment]
Thanks man, I added the lines. Should be fine now. I'm still looking into the other issue though.

**Comment by despairblue** [comment]
Yeah I'm at a loss there as well. No idea what's going wrong there :(
