### ISSUE TITLE
wrong text color in git plus command palette

### ISSUE THREAD

**Issue by despairblue** [ignism/graphite-ui#2]
![screenshot from 2014-12-25 20 25 09](https://cloud.githubusercontent.com/assets/927609/5555163/080e5bf6-8c9d-11e4-92d7-395868103930.png)

**Comment by despairblue** [comment]
Commenting out [these](https://github.com/ignism/graphite-ui/blob/master/stylesheets/ui-variables.less#L25-26) lines fixes the error, though that's not a fix as such.

Hope that helps.

**Comment by ignism** [comment]
Problem is Git Plus doesn't use the normal model overlay. Checking now how it is called and will implement it in future versions.

**Comment by ignism** [comment]
As of v0.9.1 I updated the modal panels, including a small fix for git-plus, could you be so kind to verify this fix?

**Comment by despairblue** [comment]
Hi, just tested 0.9.3 and it still occurs, by the way also with the project
quick open panel. Themes I tested that do work except from the standard
themes are fantasy ui, quantum ui and seti ui. I just couldn't figure out
what they do differently oO

**Comment by ignism** [comment]
thanks for checking, I will dive into the other ui's code when I got the time!

**Comment by ignism** [comment]
in which menu does it happen? when I press cmd-shift-h I see the following: 
![screen shot 2015-01-12 at 18 13 30](https://cloud.githubusercontent.com/assets/2485645/5707202/10fd6412-9a87-11e4-83cd-518a3ba53ccf.png)

**Comment by despairblue** [comment]
Try typing something, the selected line says `Add And Commit`:

![ss1](https://cloud.githubusercontent.com/assets/927609/5724943/646e3acc-9b4f-11e4-99fb-5c238f2ceb18.png)

**Comment by despairblue** [comment]
And this is `Project Quick Open` and the selected line is `autocomplete-plus`:
![ss2](https://cloud.githubusercontent.com/assets/927609/5724971/9cc026f6-9b4f-11e4-8652-a259fb35f974.png)

**Comment by ignism** [comment]
Should be fixed now! I celebrated it with a minor version, go grab 0.10.X

**Comment by despairblue** [comment]
Thanks man :tada:
