### ISSUE TITLE
Issues when Shadow DOM is activated on Linux

### ISSUE THREAD

**Issue by k4nar** [ignism/graphite-ui#3]
Hi,
I'm using your theme with Atom 0.166 on Linux, and when the Shadow-DOM is activated I don't get the styled scrollbars and I have a different rendering of the editor

With the Shadow-DOM:
![onitu3](https://cloud.githubusercontent.com/assets/2692721/5636850/4c7d8d9a-95f6-11e4-848b-0524b6a36fbd.png)

Without:
![onitu4](https://cloud.githubusercontent.com/assets/2692721/5636883/96274472-95f6-11e4-9048-a769a0dd3256.png)

**Comment by ignism** [comment]
Should be fixed as of now, please update to the latest version.

**Comment by k4nar** [comment]
Yep it works, thanks :) .
