### ISSUE TITLE
Wrong modified-file detection in the tree-view

### ISSUE THREAD

**Issue by k4nar** [ignism/graphite-ui#4]
Hi,
When using this theme, some directories are marked as updated in the tree-view even though they're not.

With graphite-ui:
![onitu5](https://cloud.githubusercontent.com/assets/2692721/5636968/49528598-95f7-11e4-85ae-57a12dd0bc31.png)

With atom-dark:
![onitu6](https://cloud.githubusercontent.com/assets/2692721/5636974/500236ea-95f7-11e4-9280-4b1a1d818764.png)

Thanks for making this awesome theme anyway !

**Comment by ignism** [comment]
Thanks dude. Fixed with patch v0.8.4

**Comment by k4nar** [comment]
:+1:
